name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
permissions:
  actions: write
  id-token: write
  contents: write
jobs:
  pre-release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - id: vars
        run: |
          VERSION=${{ github.event.inputs.version }}
          mvn --batch-mode -ntp dependency:go-offline
          mvn --batch-mode versions:set -DnewVersion=${VERSION}
          mvn --batch-mode versions:commit
          git config --global user.name "Hubot"
          git config --global user.email "hubot@libertyglobal.com"
          git commit -a -m "[CI] Release ${VERSION}"
          git push origin master
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT
  release:
    needs: [ pre-release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - run: mvn --batch-mode deploy -DaltDeploymentRepository=local::file:./target/staging-deploy
      - uses: jreleaser/release-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.pre-release.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
  post-release:
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - run: |
          mvn --batch-mode versions:set -DnextSnapshot -DnextSnapshotIndexToIncrement=3
          mvn --batch-mode versions:commit
          git config --global user.name "Hubot"
          git config --global user.email "hubot@libertyglobal.com"
          git commit -a -m "[CI] Prepare for next development iteration"
          git push origin master
